name: Godot CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.6.3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run GDScript Linter
        run: |
          godot --headless -s res://addons/gdscript-linter/analyzer/analyze-cli.gd
